models:
  - name: int_sales_prep
    description: "Intermediate table for sales preparation adding surrogate keys for the DIM model."
    columns:
      - name: sale_id
        description: "Unique transaction hash key."
        tests:
          - unique
          - not_null
      
      - name: sales_person_id
        description: "Hash key that identifies the sales person."
        tests:
          - not_null
      
      - name: car_id
        description: "Hash key that identifies the car."
        tests:
          - not_null
      
      - name: sale_date
        tests:
          - not_null
      
      - name: sale_price
        tests:
          - not_null