models:
  - name: int_sales_prep
    description: "Intermediate table for sales preparation adding surrogate keys for the DIM model."
    columns:
      - name: sale_id
        description: "Unique transaction hash key."
        data_tests:
          - unique
          - not_null
      
      - name: sales_person_id
        description: "Hash key that identifies the sales person."
        data_tests:
          - not_null
      
      - name: car_id
        description: "Hash key that identifies the car."
        data_tests:
          - not_null
      
      - name: sale_date
        data_tests:
          - not_null
      
      - name: sale_price
        data_tests:
          - not_null